FROM eclipse-temurin:17-jre-jammy

# 替换为阿里云镜像源
RUN sed -i "s@http://.*archive.ubuntu.com@http://mirrors.aliyun.com@g" /etc/apt/sources.list && \
    sed -i "s@http://.*security.ubuntu.com@http://mirrors.aliyun.com@g" /etc/apt/sources.list

# 安装依赖
RUN mkdir -p /app && \
    apt-get update && \
    apt-get install -y --no-install-recommends nginx dos2unix && \
    rm -rf /var/lib/apt/lists/*

# 设置时区
RUN ln -snf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo Asia/Shanghai > /etc/timezone

# 复制启动脚本并设置权限
COPY start.sh /start.sh
RUN dos2unix /start.sh && \
    chmod 755 /start.sh

# 设置工作目录
WORKDIR /app

# 复制应用文件
COPY ./AegisCompanion/target/*.jar /app/app.jar
COPY ./frontend/dist /usr/share/nginx/html
COPY ./frontend/nginx.conf /etc/nginx/conf.d/default.conf

# 暴露端口
EXPOSE 80 8090

# 使用 root 用户运行
ENTRYPOINT ["/start.sh"]
