services:
  app:
    build: .
    image: aegis-companion
    container_name: AegisCompanion
    ports:
      - "80:80"
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/AegisCompanion?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin@1234
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_REDIS_HOST: redis
      CHAT_API_KEY: ${CHAT_API_KEY}
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:  # 所有服务需共享同一网络
      - aegis-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin@1234
      MYSQL_DATABASE: AegisCompanion
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - aegis-network

  rabbitmq:
    image: rabbitmq:4.0.7-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_mqtt tcp_listeners [1883] -rabbitmq_stomp tcp_listeners [61613]"
    ports:
      - "61613:61613"
      - "1883:1883"
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - aegis-network

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - aegis-network

volumes:
  mysql_data:

networks:
  aegis-network:  # 定义共享网络
